In [ ]:
-len
min
max 
sum
mean
- median 
- mode
- square
- square root
- variance
- std
- covariance
- covaraiance-corelation
- distance between two points
- round off using numpy
- dot product two arrays

In [3]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [7]:
np.len(arr)

AttributeError: module 'numpy' has no attribute 'len'

In [9]:
np.min(arr)

10

In [11]:
np.max(arr)

40

In [13]:
np.sum(arr)

100

In [15]:
np.mean(arr)

25.0

In [19]:
np.median(arr)

25.0

In [21]:
np.mode(arr)

AttributeError: module 'numpy' has no attribute 'mode'

In [23]:
np.square(arr)

array([ 100,  400,  900, 1600])

In [27]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [31]:
np.var(arr)

125.0

In [33]:
np.std(arr)

11.180339887498949

In [37]:
np.cov(arr)

array(166.66666667)

In [63]:
np.correlate(arr[2],arr[3])

ValueError: object of too small depth for desired array

In [65]:
l1=[10,20,30,40]
l2=[20,40,50,50]
arr1=np.array(l1)
arr2=np.array(l2)
arr1*arr2

array([ 200,  800, 1500, 2000])

In [71]:
l1=[10,20,30,40]
l2=[20,40,50,50]
arr1=np.array(l1)
arr2=np.array(l2)
np.correlate(arr1,arr2)

array([4500])

In [75]:
l1=[12.34,23.45,45.56]
l2=[34.45,23.45,56.67]
arr1=np.array(l1)
arr2=np.array(l2)
arr=arr1*arr2
np.round(arr,2)

array([ 425.11,  549.9 , 2581.89])

In [79]:
l=[10,20,30,40,50]
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [81]:
np.var(arr)

200.0

In [83]:
np.mean(arr)

30.0

In [107]:
#step-1: xbar
arr0=np.mean(arr)
arr0
#step-2: x-xbar
arr1=arr-arr0
arr1
#stap-3: (x-xbar)^2
arr2=np.square(arr1)
arr2
#step-4:summation((x-xbar)^2)
arr3=np.sum(arr2)
arr3
#step-5: sum
arr4=arr3/len(arr)
arr4

200.0

In [115]:
np.sum(np.square(arr-np.mean(arr)))/len(arr)

200.0

**distance between two points**

In [128]:
p1=(10,20)
p2=(5,6)
np.sqrt(np.square(np.subtract(p2[0],p1[0]))+np.square(np.subtract(p2[1],p1[1])))


14.866068747318506

In [134]:
p1=(10,20)
p2=(5,6)
arr1=np.array(p1)
arr2=np.array(p2)
np.sqrt(np.sum(np.square(arr1-arr2)))

14.866068747318506

In [138]:
import numpy as np
np.linalg.norm(arr1-arr2)

14.866068747318506

In [ ]:
x^2-5x+6

op=3 ,2

a=1,b=-5,c=6

In [23]:
import numpy as np
a,b,c=1,-5,6
arr1=np.sqrt(np.square(b)-4*a*c)
arr2=(-(b)+arr1)/2*a
arr3=(-(b)-arr1)/2*a
print(arr2,arr3)



3.0 2.0
