In [1]:
import numpy as np
l1=[10,20,30,40]
arr1=np.array(l1)
arr1

array([10, 20, 30, 40])

In [3]:
len(arr1)

4

**shape-dimensions**

In [6]:
arr1.ndim # one list so one dimension

1

In [8]:

arr1.shape

(4,)

In [10]:
l=[[10,20,30,40]]
arr2=np.array(l)
print(arr2)
print(len(arr2))
print(arr2.ndim)
print(arr2.shape)

[[10 20 30 40]]
1
2
(1, 4)


In [12]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[l1,l2]
arr2=np.array(l)
print(arr2)
print(len(arr2))
print(arr2.ndim)
print(arr2.shape)

[[10 20 30 40]
 [ 1  2  3  4]]
2
2
(2, 4)


In [18]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=['A','B','C','D']
l=[l1,l2,l3]
arr2=np.array(l)
print(arr2)
print(len(arr2))
print(arr2.ndim)
print(arr2.shape)

[['10' '20' '30' '40']
 ['1' '2' '3' '4']
 ['A' 'B' 'C' 'D']]
3
2
(3, 4)


In [22]:
l=[[  [10,20,30,40],
   [1,2,3,4],
   ['A','B','C','D']
  ]]
arr2=np.array(l)
print(arr2)
print(len(arr2))
print(arr2.ndim)
print(arr2.shape)

[[['10' '20' '30' '40']
  ['1' '2' '3' '4']
  ['A' 'B' 'C' 'D']]]
1
3
(1, 3, 4)


In [32]:
l=[[  [10,20,30,40],
   [1,2,3,4],
   ['A','B','C','D']
  ],[  [10,20,30,40],
   [1,2,3,4],
   ['A','B','C','D']
  ],[  [10,20,30,40],
   [1,2,3,4],
   ['A','B','C','D']
  ],]
arr2=np.array(l)
print(arr2)
print(len(arr2))
print(arr2.ndim)
print(arr2.shape)

[[['10' '20' '30' '40']
  ['1' '2' '3' '4']
  ['A' 'B' 'C' 'D']]

 [['10' '20' '30' '40']
  ['1' '2' '3' '4']
  ['A' 'B' 'C' 'D']]

 [['10' '20' '30' '40']
  ['1' '2' '3' '4']
  ['A' 'B' 'C' 'D']]]
3
3
(3, 3, 4)


In [30]:
l=[[[  [10,20,30,40],
   [1,2,3,4],
   ['A','B','C','D']
  ],[  [10,20,30,40],
   [1,2,3,4],
   ['A','B','C','D']
  ]
  ]]
arr2=np.array(l)
print(arr2)
print(len(arr2))
print(arr2.ndim)
print(arr2.shape)

[[[['10' '20' '30' '40']
   ['1' '2' '3' '4']
   ['A' 'B' 'C' 'D']]

  [['10' '20' '30' '40']
   ['1' '2' '3' '4']
   ['A' 'B' 'C' 'D']]]]
1
4
(1, 2, 3, 4)


In [38]:
l=[[[  [10,20,30,40,50],
   [1,2,3,4,5],
   ['A','B','C','D','e'],
    [23,45,67,78,56] 
  ],[  [10,20,30,40,50],
   [1,2,3,4,5],
   ['A','B','C','D','e'],
     [23,45,67,78,56] 
  ],[  [10,20,30,40,50],
   [1,2,3,4,5],
   ['A','B','C','D','e'],[23,45,67,78,56] 
  ],
  ],[[  [10,20,30,40,50],
   [1,2,3,4,5],
   ['A','B','C','D','e'],
      [23,45,67,78,56] 
  ],[  [10,20,30,40,50],
   [1,2,3,4,5],
   ['A','B','C','D','e'],[23,45,67,78,56] 
  ],[  [10,20,30,40,50],
   [1,2,3,4,5],
   ['A','B','C','D','e'],
     [23,45,67,78,56] 
  ]]]
arr2=np.array(l)
print(arr2)
print(len(arr2))
print(arr2.ndim)
print(arr2.shape)

[[[['10' '20' '30' '40' '50']
   ['1' '2' '3' '4' '5']
   ['A' 'B' 'C' 'D' 'e']
   ['23' '45' '67' '78' '56']]

  [['10' '20' '30' '40' '50']
   ['1' '2' '3' '4' '5']
   ['A' 'B' 'C' 'D' 'e']
   ['23' '45' '67' '78' '56']]

  [['10' '20' '30' '40' '50']
   ['1' '2' '3' '4' '5']
   ['A' 'B' 'C' 'D' 'e']
   ['23' '45' '67' '78' '56']]]


 [[['10' '20' '30' '40' '50']
   ['1' '2' '3' '4' '5']
   ['A' 'B' 'C' 'D' 'e']
   ['23' '45' '67' '78' '56']]

  [['10' '20' '30' '40' '50']
   ['1' '2' '3' '4' '5']
   ['A' 'B' 'C' 'D' 'e']
   ['23' '45' '67' '78' '56']]

  [['10' '20' '30' '40' '50']
   ['1' '2' '3' '4' '5']
   ['A' 'B' 'C' 'D' 'e']
   ['23' '45' '67' '78' '56']]]]
2
4
(2, 3, 4, 5)


In [42]:
l1=10
l=[l1,l1]
l

[10, 10]

In [52]:
l= [10] 
l1=[l,l]
l2=[l1,l1,l1]
l3=[l2,l2,l2,l2]
l4=[l3,l3,l3,l3,l3]
arr2=np.array(l4)
print(arr2)
print(len(arr2))
print(arr2.ndim)
print(arr2.shape)

[[[[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]]



 [[[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]]



 [[[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]]



 [[[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]


  [[[10]
    [10]]

   [[10]
    [10]]

   [[10]
    [10]]]]



