## Numpy
- Numpy: Numerical python

- we already seen math packages

- Numpy also similar to math package

- But Numpy works with arrays

- it is used for high level math computations

- we can make elements in multiple ways

    - List : Basic python

    - Tuple : Basic python

    - arrays : Numpy

    - tensors : Tensorflow or torch

In [ ]:
l1=[10,20,30,40]
t1=(10,20,30,40)
array({10,20,30,40])
tensor([10,20,30,40])

In [3]:
import numpy as np 
l1=[10,20,30,40]
np.array(l1)

array([10, 20, 30, 40])

In [5]:
import numpy as np 
t1=(10,20,30,40)
np.array(l1)

array([10, 20, 30, 40])

In [17]:
l1=[10,20,30,40]
l2=[100,200,300,400]
[i+j for i,j in zip(l1,l2)]

[110, 220, 330, 440]

In [19]:
l1=[10,20,30,40]
l2=[100,200,300,400]
arr1=np.array(l1)
arr2=np.array(l2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[110 220 330 440]
[ -90 -180 -270 -360]
[ 1000  4000  9000 16000]
[0.1 0.1 0.1 0.1]


**use case-2**

In [28]:
import time
start=time.time()
l1=list(range(100000000))
l2=list(range(100000000))
[i*j for i,j in zip(l1,l2)]
end=time.time()
print('total time:',(end-start))

total time: 56.98832178115845


In [1]:
import time
import numpy as np
start=time.time()
l1=list(range(10000000))
arr1=np.array(l1)
l2=list(range(10000000))
arr2=np.array(l2)
[i*j for i,j in zip(l1,l2)]
end=time.time()
print('total time:',(end-start))

total time: 1.6116485595703125


In [6]:
import time
import numpy as np
start=time.time()
arr1=np.arange(10000000)
arr2=np.arange(10000000)
[i*j for i,j in zip(l1,l2)]
end=time.time()
print('total time:',(end-start))

total time: 0.7625222206115723
